sudo: false
services:
    - postgresql
before_script:
    - psql -c 'create database chat_client_test;' -U postgres

language: python
python:
    - "2.7.11"

language: node_js
node_js:
    - "4.3"

install: 
    - pip install --user -r requirements.txt
    - npm install jasmine
script:
    - python -m unittest discover -p "*_test.py"
    - npm test


