sudo: false
services:
    - postgresql
before_script:
    - psql -c 'create database chat-client-test;' -U postgres

language: python
python:
    - "2.7.11"
install: "pip install --user -r requirements.txt"
script: python -m unittest discover -p "*_test.py"

language: node_js
node_js:
    - "4.3"

